Repository ci2-ipt/Ci2-CRIS, pull requests merged in 2023-02, with the labels that each got.

#79 ci2-cris-22: article project association (m-n)
  .gitattributes
  .idea/Ci2-CRIS.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  1_src/app/controllers/articles_controller.rb
  1_src/app/models/article.rb
  1_src/app/models/articles_project.rb
  1_src/app/models/project.rb
  1_src/app/models/researcher.rb
  1_src/app/views/articles/Projects.html.erb
  1_src/app/views/articles/_formArticle.html.erb
  1_src/app/views/articles/_formEditArticle.html.erb
  1_src/app/views/articles/_showArticle.html.erb
  1_src/app/views/articles/show.html.erb
  1_src/app/views/home/index.html.erb
  1_src/app/views/projects/show.html.erb
  1_src/app/views/researchers/show.html.erb
  1_src/db/migrate/20230128171544_add_project_ref_to_articles.rb
  1_src/db/migrate/20230204212637_create_articles_projects.rb
  1_src/db/schema.rb
  1_src/db/seeds.rb
  1_src/erd.png
  1_src/test/fixtures/articles_projects.yml
  1_src/test/models/articles_project_test.rb
Labels: backend, Association, Fix

#81 ci2 cris 80-adding missing migrations
  1_src/app/models/articles_researcher.rb
  1_src/config/routes.rb
  1_src/db/migrate/20230205173154_create_articles_researchers.rb
  1_src/db/migrate/20230205174258_remove_authors_from_articles.rb
  1_src/db/schema.rb
  1_src/test/fixtures/articles_researchers.yml
  1_src/test/models/articles_researcher_test.rb
Labels: Fix

#88 ci2 cris 78-tornar secção artigos visualmente consumível
  .idea/.gitignore
  1_src/.gitignore
  1_src/app/controllers/researchers_controller.rb
  1_src/app/models/article.rb
  1_src/app/models/institution.rb
  1_src/app/models/institutions_researcher.rb
  1_src/app/models/researcher.rb
  1_src/app/views/articles/_listArticles.html.erb
  1_src/app/views/articles/_showArticle.html.erb
  1_src/app/views/articles/index.html.erb
  1_src/app/views/articles/listSelect.html.erb
  1_src/app/views/articles/show.html.erb
  1_src/app/views/projects/show.html.erb
  1_src/app/views/researchers/_form.html.erb
  1_src/app/views/researchers/show.html.erb
  1_src/config/routes.rb
  1_src/db/migrate/20230219141457_create_institutions_researchers.rb
  1_src/db/schema.rb
  1_src/db/seeds.rb
  1_src/erd.png
  1_src/test/fixtures/institutions_researchers.yml
  1_src/test/models/institutions_researcher_test.rb
Labels: frontend

#87 ci2 cris-11/associacao investigador centro
  1_src/app/views/researchers/show.html.erb
  1_src/erd.png
Labels: backend, Association

#92 Feature/ci2 cris 45/pagination
  1_src/.byebug_history
  1_src/app/assets/images/Cognition.png
  1_src/app/assets/images/GePISCal.png
  1_src/app/assets/images/MoSBurn.png
  1_src/app/assets/images/Solar.png
  1_src/app/assets/images/vitasenior.png
  1_src/app/assets/stylesheets/main.css
  1_src/app/controllers/projects_controller.rb
  1_src/app/javascript/controllers/slim_controller.js
  1_src/app/views/home/index.html.erb
  1_src/app/views/institutions/_formInst.html.erb
  1_src/app/views/projects/_form.html.erb
  1_src/app/views/projects/filter.html.erb
  1_src/app/views/projects/index.html.erb
  1_src/app/views/projects/show.html.erb
  1_src/db/seeds.rb
Labels: bug, backend

#94 ci2-cris-85/alterar atributo keywords para taggable
  .idea/Ci2-CRIS.iml
  1_src/.byebug_history
  1_src/Gemfile
  1_src/Gemfile.lock
  1_src/app/controllers/articles_controller.rb
  1_src/app/models/article.rb
  1_src/app/views/articles/_formArticle.html.erb
  1_src/app/views/articles/_formEditArticle.html.erb
  1_src/app/views/articles/_showArticle.html.erb
  1_src/app/views/articles/index.html.erb
  1_src/config/routes.rb
  1_src/db/migrate/20230224235932_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
  1_src/db/migrate/20230224235933_add_missing_unique_indices.acts_as_taggable_on_engine.rb
  1_src/db/migrate/20230224235934_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
  1_src/db/migrate/20230224235935_add_missing_taggable_index.acts_as_taggable_on_engine.rb
  1_src/db/migrate/20230224235936_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
  1_src/db/migrate/20230224235937_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
  1_src/db/migrate/20230224235938_add_tenant_to_taggings.acts_as_taggable_on_engine.rb
  1_src/db/schema.rb
Labels: backend, frontend

#93 ci2-cris-75: criação do modelo vagas com parâmetros adequados
  1_src/.byebug_history
  1_src/app/controllers/vacancies_controller.rb
  1_src/app/helpers/vacancies_helper.rb
  1_src/app/models/institution.rb
  1_src/app/models/project.rb
  1_src/app/models/researcher.rb
  1_src/app/models/vacancy.rb
  1_src/app/views/home/index.html.erb
  1_src/app/views/researchers/index.html.erb
  1_src/app/views/vacancies/_form.html.erb
  1_src/app/views/vacancies/_vacancy.html.erb
  1_src/app/views/vacancies/edit.html.erb
  1_src/app/views/vacancies/index.html.erb
  1_src/app/views/vacancies/new.html.erb
  1_src/app/views/vacancies/show.html.erb
  1_src/config/routes.rb
  1_src/db/migrate/20221218170725_create_projects.rb
  1_src/db/migrate/20230130204713_create_vacancies.rb
  1_src/db/migrate/20230206164422_vacancy_researcher.rb
  1_src/db/schema.rb
  1_src/test/controllers/vacancies_controller_test.rb
  1_src/test/fixtures/vacancies.yml
  1_src/test/models/vacancy_test.rb
  1_src/test/system/vacancies_test.rb
Labels: backend, frontend, Association

#97 ci2.cris-XX/Fix do main
  1_src/app/models/institution.rb
  1_src/app/models/project.rb
  1_src/app/views/projects/index.html.erb
  1_src/db/migrate/20221218170725_create_projects.rb
  1_src/db/schema.rb
  1_src/db/seeds.rb
Labels: bug, Fix
